version: 2.1

orbs:
  orb-tools: circleci/orb-tools@9.0.0
  # Integration tests
  secrethub: secrethub/cli@<<pipeline.parameters.dev-orb-version>>
  aws-cli: circleci/aws-cli@0.1.22

parameters:
  run-integration-tests:
    type: boolean
    default: false
    description: >
      Whether or not to run the orb integration tests. Defaults to false to make sure a dev orb version of the latest commit gets published first.
      The 'orb-tools/trigger-integration-tests-workflow' job kicks off the integration tests, by triggering a new workflow with this parameter set to 'true'.
  dev-orb-version:
    type: string
    default: "dev:alpha"
    description: >
      The SecretHub dev orb version to use in the integration tests. Default is "dev:alpha" for the initial config validation to pass.
      The 'orb-tools/trigger-integration-tests-workflow' job will override this parameter with "dev:${CIRCLE_SHA1:0:7}", so that the integration tests
      are always ran with the correct orb code. The scheduled 'keep-dev-orb' workflow will make sure the dev:alpha orb doesn't expire.

orb_promotion_filters: &orb_promotion_filters
  branches:
    ignore: /.*/
  tags:
    only: /^v[0-9]+\.[0-9]+\.[0-9]+$/

jobs:
  test-integration-exec:
    docker:
      - image: cimg/base:stable
    environment:
      SECRET: secrethub://company/app/secret
    steps:
      - checkout
      - secrethub/exec:
          step-name: Validate if secret is set correctly
          command: |
            if [ $SECRET != "DDXLKkBhprQgW7w7OFsM8y" ]; then
              echo "secret is not correctly set"
              exit 1
            fi
  test-integration-other-orb:
    executor: aws-cli/default
    shell: secrethub run -- /bin/bash
    environment:
      AWS_DEFAULT_REGION: us-east-1
      AWS_ACCESS_KEY_ID: secrethub://company/app/aws/access_key_id
      AWS_SECRET_ACCESS_KEY: secrethub://company/app/aws/secret_access_key
    steps:
      - secrethub/install
      - checkout
      - aws-cli/setup
  test-integration-env-export:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - secrethub/env-export:
          var-name: SECRET
          secret-path: company/app/secret
      - run:
          name: Validate if secret is set correctly
          command: |
            if [ $SECRET != "DDXLKkBhprQgW7w7OFsM8y" ]; then
              echo "secret is not correctly set"
              exit 1
            fi
      - secrethub/env-export:
          var-name: MULTILINE_SECRET
          secret-path: company/app/multiline_secret
      - run:
          name: Validate if multiline secret is set correctly
          environment:
            MULTILINE_SECRET_EXPECTED: |-
              4dAXbmYWiLkyYpExLnhGRD9wA7
              rsrNbNYprQZHz8Vtgu4fJezGDB
          command: |
            if [ "$MULTILINE_SECRET" != "$MULTILINE_SECRET_EXPECTED" ]; then
              echo "secret is not correctly set"
              exit 1
            fi

workflows:
  validate_publish-dev:
    unless: << pipeline.parameters.run-integration-tests >>
    jobs:
      - orb-tools/lint
      - orb-tools/pack
      - orb-tools/publish-dev:
          orb-name: secrethub/cli
          context: publish-orb-dev
          publish-alpha-version: true
          publish-sha-version: true
          requires:
            - orb-tools/lint
            - orb-tools/pack
      - orb-tools/trigger-integration-tests-workflow:
          name: trigger-integration-tests
          context: publish-orb-dev
          requires:
            - orb-tools/publish-dev

  test-integration:
    when: << pipeline.parameters.run-integration-tests >>
    jobs:
      - test-integration-exec
      - test-integration-other-orb
      - test-integration-env-export

  # Republish the dev:alpha orb every month to ensure new pipelines don't get rejected due to expired dev orbs.
  keep-dev-orb:
    triggers:
      - schedule:
          cron: "0 0 1 * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - orb-tools/publish-dev:
          orb-name: secrethub/cli
          context: publish-orb-dev
          publish-alpha-version: true
          publish-sha-version: false

  publish-to-registry:
    unless: << pipeline.parameters.run-integration-tests >>
    jobs:
      - approve:
          type: approval
          filters: *orb_promotion_filters
      - orb-tools/dev-promote-prod-from-git-tag:
          name: publish-to-registry
          orb-name: secrethub/cli
          context: publish-orb-prd
          add-pr-comment: false
          major-release-tag-regex: '^v[1-9][0-9]*\.0\.0+$'
          minor-release-tag-regex: '^v[0-9]*\.[1-9][0-9]*\.0+$'
          patch-release-tag-regex: '^v[0-9]*\.[0-9]*\.[1-9][0-9]*$'
          requires:
            - approve
          filters: *orb_promotion_filters
