version: 2.1

orbs:
  orb-tools: circleci/orb-tools@9.0.0

workflows:
  validate_publish-dev:
    jobs:
      - orb-tools/lint
      - orb-tools/pack:
          requires:
            - orb-tools/lint
      - orb-tools/publish-dev:
          orb-name: secrethub/cli
          context: publish-orb-dev
          alpha-version-ref: dev:latest
          publish-sha-version: false
          requires:
            - orb-tools/pack
