version: 2.1

orbs:
  orb-tools: circleci/orb-tools@9.0.0
  # Integration tests
  secrethub: secrethub/cli@<<pipeline.parameters.dev-orb-version>>
  aws-cli: circleci/aws-cli@0.1.22

parameters:
  run-integration-tests:
    type: boolean
    default: false
  dev-orb-version:
    type: string
    default: "dev:latest"

jobs:
  test-integration-exec:
    docker:
      - image: cimg/base:stable
    environment:
      DOCKER_USERNAME: secrethub://company/app/docker/username
      DOCKER_PASSWORD: secrethub://company/app/docker/password
    steps:
      - checkout
      - secrethub/exec:
          step-name: Validate if secrets have been provisioned
          command: |
            set -e
            : ${DOCKER_USERNAME:?DOCKER_USERNAME is not set}
            : ${DOCKER_PASSWORD:?DOCKER_PASSWORD is not set}
  test-integration-other-orb:
    executor: aws-cli/default
    shell: secrethub run -- /bin/bash
    environment:
      AWS_DEFAULT_REGION: us-east-1
      AWS_ACCESS_KEY_ID: secrethub://company/app/aws/access_key_id
      AWS_SECRET_ACCESS_KEY: secrethub://company/app/aws/secret_access_key
    steps:
      - secrethub/install
      - checkout
      - aws-cli/setup

workflows:
  validate_publish-dev:
    unless: << pipeline.parameters.run-integration-tests >>
    jobs:
      - orb-tools/lint
      - orb-tools/pack
      - orb-tools/publish-dev:
          name: publish-dev-sha
          orb-name: secrethub/cli
          context: publish-orb-dev
          publish-alpha-version: false
          publish-sha-version: true
          requires:
            - orb-tools/lint
            - orb-tools/pack
      - orb-tools/publish-dev:
          name: publish-dev-latest
          orb-name: secrethub/cli
          context: publish-orb-dev
          publish-alpha-version: true
          alpha-version-ref: dev:latest
          publish-sha-version: false
          requires:
            - publish-dev-sha
          filters:
            branches:
              only: master
      - orb-tools/trigger-integration-tests-workflow:
          name: trigger-integration-tests
          context: publish-orb-dev
          requires:
            - publish-dev-sha

  test-integration_publish-to-registry:
    when: << pipeline.parameters.run-integration-tests >>
    jobs:
      - test-integration-exec
      - test-integration-other-orb
      - orb-tools/dev-promote-prod-from-git-tag:
          name: publish-to-registry
          orb-name: secrethub/cli
          context: publish-orb-prd
          add-pr-comment: false
          major-release-tag-regex: '^major-v[[:digit:]]+\.[[:digit:]]+\.[[:digit:]]+$'
          minor-release-tag-regex: '^minor-v[[:digit:]]+\.[[:digit:]]+\.[[:digit:]]+$'
          patch-release-tag-regex: '^patch-v[[:digit:]]+\.[[:digit:]]+\.[[:digit:]]+$'
          requires:
            - test-integration-exec
            - test-integration-other-orb
          filters:
            branches:
              only: master
            tags:
              only: /^(major|minor|patch)-v\d+\.\d+\.\d+$/
