version: 2.1

orbs:
  orb-tools: circleci/orb-tools@9.0.0
  # Integration tests
  secrethub: secrethub/cli@<<pipeline.parameters.dev-orb-version>>
  aws-cli: circleci/aws-cli@0.1.22

parameters:
  run-integration-tests:
    type: boolean
    default: false
    description: >
      Whether or not to run the orb integration tests. Defaults to false to make sure a dev orb version of the latest commit gets published first.
      The 'orb-tools/trigger-integration-tests-workflow' job kicks off the integration tests, by triggering a new workflow with this parameter set to 'true'.
  dev-orb-version:
    type: string
    default: 1.0.1
    description: >
      The SecretHub dev orb version to use in the integration tests.
      Default value has to be (any) stable prod version, because pipelines with dev orbs older than 90 days will get rejected.
      The 'orb-tools/trigger-integration-tests-workflow' job will override this parameter with "dev:${CIRCLE_SHA1:0:7}",
      so that the integration tests are always ran with the latest orb code, instead of the stable prod version.

orb_promotion_filters: &orb_promotion_filters
  branches:
    ignore: /.*/
  tags:
    only: /^v[0-9]+\.[0-9]+\.[0-9]+$/

jobs:
  test-integration-exec:
    docker:
      - image: cimg/base:stable
    environment:
      SECRET: secrethub://company/app/secret
    steps:
      - checkout
      - secrethub/exec:
          step-name: Validate if secret is set correctly
          command: |
            if [ $SECRET != "DDXLKkBhprQgW7w7OFsM8y" ]; then
              echo "secret is not correctly set"
              exit 1
            fi
  test-integration-other-orb:
    executor: aws-cli/default
    shell: secrethub run -- /bin/bash
    environment:
      AWS_DEFAULT_REGION: us-east-1
      AWS_ACCESS_KEY_ID: secrethub://company/app/aws/access_key_id
      AWS_SECRET_ACCESS_KEY: secrethub://company/app/aws/secret_access_key
    steps:
      - secrethub/install
      - checkout
      - aws-cli/setup

workflows:
  validate_publish-dev:
    unless: << pipeline.parameters.run-integration-tests >>
    jobs:
      - orb-tools/lint
      - orb-tools/pack
      - orb-tools/publish-dev:
          orb-name: secrethub/cli
          context: publish-orb-dev
          publish-alpha-version: true
          publish-sha-version: true
          requires:
            - orb-tools/lint
            - orb-tools/pack
      - orb-tools/trigger-integration-tests-workflow:
          name: trigger-integration-tests
          context: publish-orb-dev
          requires:
            - orb-tools/publish-dev

  test-integration:
    when: << pipeline.parameters.run-integration-tests >>
    jobs:
      - test-integration-exec
      - test-integration-other-orb

  publish-to-registry:
    unless: << pipeline.parameters.run-integration-tests >>
    jobs:
      - approve:
          type: approval
          filters: *orb_promotion_filters
      - orb-tools/dev-promote-prod-from-git-tag:
          name: publish-to-registry
          orb-name: secrethub/cli
          context: publish-orb-prd
          add-pr-comment: false
          major-release-tag-regex: '^v[1-9][0-9]*\.0\.0+$'
          minor-release-tag-regex: '^v[0-9]*\.[1-9][0-9]*\.0+$'
          patch-release-tag-regex: '^v[0-9]*\.[0-9]*\.[1-9][0-9]*$'
          requires:
            - approve
          filters: *orb_promotion_filters
