on:
  push:
    branches:
      - release/v*

jobs:
  bump-version:
    name: Bump version in YAML
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Bump version
        uses: florisvdg/action-version-bump@v0.1.0
        with:
          sed: 's/\(SECRETHUB_APP_INFO_VERSION: \).*/\1$VERSION/g'
          file: src/commands/exec.yml
          author_email: bender.github@secrethub.io
